$(document).ready(function()
{
	$('body').prepend('<div id="debug" class=""'
	+'style="'
	+ 'font-family:myriad pro, arial;font-size:12px;color:#000000;"'
	+'></div>');
	
	
	$('#debug').css({
	backgroundColor: 'white',
	position: 'fixed',
	top: 0,
	right: 0,
	padding: 10,
	borderBottom: '1px solid #565656',
	borderLeft: '1px solid #565656',
	opacity: 0.9,
	paddingRight: 20,
	paddingLeft: 20
	}) ;
    
    
    /**
     * DEBUG ROUTE
     */
    
	$('#debug').append('<div id="debug_route" style="float:left;margin-right:20px;cursor:pointer;">route info</div>');
    
    $('#debug').append('<div id="debug_route_dialog" style="" title="Route information"><?php
    
		$req = Core::get('Request')->vars['get'] ;
		echo '<div style="font-size:40px;width:100%;text-align:center;padding-top:20px;padding-bottom:20px;"><span style="color:#666;">'.Request::get('agent').'</span>/<span style="color:#999;">'.Request::get('controller').'</span>/<span style="color:#CCC;">'.Request::get('action').'</span></div>' ;
		
		foreach($req as $param => $value)
		{
			echo $param.': '.$value.'<br/>' ;
		}
	
	?></div>') ;
    
     $("#debug_route_dialog").dialog({autoOpen: false, width: 500, height: 300});
    
    $('#debug_route').click(function() {
    	$("#debug_route_dialog").dialog('open');
    }) ;
    
    
    
	
	$('#debug').append('<div id="debug_runtime" style="float:left;margin-right:20px;cursor:pointer;"><img style="display:block;margin-top:-1px;margin-right:5px;float:left;"'
	+ 'src="<?=SYSURI?>core/icons/runtime.png"/><?=$tpl->runtime?> ms</div>');
	
	$('#debug').append('<div id="debug_memory" style="float:left;"><img style="display:block;margin-top:-1px;margin-right:5px;float:left;"'
	+ 'src="<?=SYSURI?>core/icons/memory.png"/><?=$tpl->memory?> mb</div>');
	
	
	
    
    
   
    
    
    
    
	
	$('#debug').append('<br style="clear:both;"/>');

});