<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

<link href='http://fonts.googleapis.com/css?family=Ubuntu' rel='stylesheet' type='text/css'>

<title><?=$tpl->exception?></title>

<style type="text/css">

body {
	padding:0px;
	margin:0px;
}

#wrapper {
	position:absolute;
	left:40px;
	right:40px;
	top:40px;
	min-width:600px;
	max-width:1200px;
	margin:0px auto;
	margin-top:32px;
}

#head {
	height:42px;
	background-color:#2D2D2D;

	color:#ffffff;
	font-family:Ubuntu;
	padding:22px 0px 0px 20px;
	font-size:15px;
	overflow:hidden;
	
	border-top-left-radius:3px;
	border-top-right-radius:3px;
}


#logo {
	
	font-family:Ubuntu;
	text-decoration:none;
	font-size:50px;
	color:#ffffff;

	display:block;
	margin-top:-22px;
	margin-right:-1px;
	float:right;
	/*opacity:0.3;
	filter:alpha(opacity=30);*/
	overflow:hidden;
	
	height:52px;
	border-radius:3px;
	
	
	padding:6px 21px 5px 20px;
}

#logo:hover {
	background-color: #357AE8;
	background-image: -webkit-linear-gradient(top,#4d90fe,#357AE8);
	background-image: -moz-linear-gradient(top,#4d90fe,#357AE8);
	background-image: -ms-linear-gradient(top,#4d90fe,#357AE8);
	background-image: -o-linear-gradient(top,#4d90fe,#357AE8);
	background-image: linear-gradient(top,#4d90fe,#357AE8);
	border:1px solid #3079ED;
	color:#ffffff;
	padding:5px 20px 5px 20px;
}



#body {
	padding:20px 20px 20px 20px;
	font-size:12px;
	
	background-color:#F1F1F1;
	border:1px solid #D2D2D2;

	border-top:0px;

	border-bottom-left-radius:3px;
	border-bottom-right-radius:3px;

}

.trace_line {
	width:100%;	
	border-bottom:1px solid #464646;
	padding:10px 0px 3px 0px;
}

#message {
	margin-bottom:20px;
	font-size:15px;
}

#trace_head {
	font-weight:bold;
	font-size:15px;
}

.depth {
	font-size:30px;
	color:#CCC;
	float:left;
	font-family:Ubuntu;
	width:40px;
	margin-right:10px;
}
	
.trace_line:hover .depth {
	color:#999;
}

</style>



</head>
<body>

<div id="wrapper">

    <div id="head">
	
    <div id="logo">fermi</div>
	
	<?=$tpl->exception?></div>
    
    <div id="body">
    
        <div id="message">
        	<?=$tpl->message?>
        </div>
        
        
        <div id="trace_head">Stacktrace:</div>
        
        
        <div id="trace">
			<?php
            foreach($tpl->traces as $trace)
            {
				
            ?>
                <div class="trace_line">
                
                <div class="depth"><?php
				
                if((int)$trace['depth'] < 10)
				{
					$trace['depth'] = '0'.$trace['depth'] ;
				}
				
				echo $trace['depth'] ;
				
				?></div>
                
                <strong><?=$trace['file']?></strong> in line <strong><?=$trace['line']?></strong><br/>
                &nbsp;&nbsp;&rArr; <strong><?=$trace['function']?></strong>
                    
                </div>
            <?php
            }
            ?>
        </div>
        
    </div>

</div>

</body>
</html>