<tr>
	<td>
	<label for="<?=$tpl->name?>">
	<?php
	
	if(isset($tpl->label))
	{
		echo '<span class="form_label">'.I18n::_($tpl->label).''.$tpl->required.'</span>' ;
	}
	
	if(isset($tpl->comment))
	{
		echo '<span class="form_comment">'.I18n::_($tpl->comment).'</span>' ;
	}
	
	
	?>
	</label>
	</td>
	<td>
		<input type="file" name="<?=$tpl->name?>" id="<?=$tpl->name?>" class="<?=$tpl->class?>" style="<?=$tpl->style?>" />
		<?php
		
		if(isset($tpl->value) AND !empty($tpl->value))
		{
			echo '<br/>
			<a href="#" onclick="$(\'#window-lightbox_'.$tpl->name.'\').dialog(\'open\') ; return false ;">
				<img src="'.$tpl->sysuri.'image.php?image=/media/'.$tpl->value.'&amp;width=100" style="width:100px" />
			</a>' ;
		}
		
		?>
		
		<div id="window-lightbox_<?=$tpl->name?>" style="text-align:center;" title="<?=htmlentities($tpl->value)?>">
			<img style="display:block;width:96%;margin:0px auto;margin-top:20px;margin-bottom:20px;" src="" />
		</div>

		<script type="text/javascript">
		$(document).ready(function() { 

			$("#window-lightbox_<?=$tpl->name?>" ).dialog({
					position: ['center', 200],
					resizable: true,
					draggable: true,
					width: 1000,
					modal: false,
					autoOpen: false,
					open: function() {
						$(this).children('img').attr('src', '<?=$tpl->sysuri?>media/<?=$tpl->value?>') ;
					}
			});


		});
		</script>
	</td>
</tr>