<tr>
	<td>
	<label for="<?=$tpl->name?>">
	<?php
	
	if(isset($tpl->label))
	{
		echo '<span class="form_label">'.I18n::_($tpl->label).''.$tpl->required.'</span>' ;
	}
	
	if(isset($tpl->comment))
	{
		echo '<span class="form_comment">'.I18n::_($tpl->label).'</span>' ;
	}
	
	
	?>
	</label>
	</td>
	<td><input type="password" id="<?=$tpl->name?>" name="<?=$tpl->name?>" value="<?=$tpl->value?>" class="<?=$tpl->class?>"></input></td>
</tr>