<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

<title><?=$tpl->title?></title>

<link href='http://fonts.googleapis.com/css?family=Ubuntu' rel='stylesheet' type='text/css'>

<link rel="stylesheet" href="<?=$tpl->skin?>/reset.css" type="text/css" />
<link rel="stylesheet" href="<?=$tpl->skin?>/style.css" type="text/css" />

<?=$tpl->aux_head?>

<script type="text/javascript" src="<?=$tpl->skin?>/easing.js"></script>

<script type="text/javascript" src="<?=$tpl->skin?>/jquery.scrollTo-min.js"></script> 
<script type="text/javascript" src="<?=$tpl->skin?>/init.js"></script> 


<?=$tpl->aux_js?>

</head>
<body>


	<div id="wrapper">
    
    	<div id="header">
        	
            <a id="logo" href="<?=$tpl->link('admin/dashboard/index')?>">fermi</a>
            
            <div id="welcome">
            
            	<span><?=I18n::_('admin_panel_top_welcome_back')?>, Paul</span>
                <a href="<?=$tpl->link('admin/panel/logout')?>"><?=I18n::_('admin_panel_top_logout')?></a>
                 <a href="<?=SYSURI?>"><?=I18n::_('admin_panel_top_frontpage')?></a>
            
            </div>
            
            <div id="nav">
            	<?php
					$current = strtolower(Request::get('agent').'/'.Request::get('controller')) ;
				
					foreach(Admin::getSections() as $section => $values)
					{
						if(strpos($values['target'], $current) === 0)
						{
							$active = ' active' ;
						}
						else
						{
							$active = '' ;
						}
						
						echo '<span class="nav'.$active.'">
                			<a href="'.$tpl->link($values['target']).'" class="title">'.I18n::_($values['label']).'</a>' ;
						
						if($items = Admin::getItems($section))
						{
							echo '<span class="sub">' ;
							foreach($items as $item)
							{
								echo '<a href="'.$tpl->link($item['target']).'">'.I18n::_($item['label']).'</a>' ;
							}
							echo '</span>' ;
						}
                		echo '</span>' ;
					}
				
				?>
           
            </div>

        </div>
    
    	<div id="actions">
        
        	<span class="up"></span>
        
        	<a href="#">
            	<span class="icon" style="background-image:url(<?=$tpl->skin?>/img/back.png);"></span>
                <?=I18n::_('admin_action_back')?>
            </a>
            
            <a href="#">
            	<span class="icon" style="background-image:url(<?=$tpl->skin?>/img/cancel.png);"></span>
                 <?=I18n::_('admin_action_cancel')?>
            </a>
            
            <a href="#">
            	<span class="icon" style="background-image:url(<?=$tpl->skin?>/img/save.png);"></span>
                 <?=I18n::_('admin_action_save')?>
            </a>
        
        </div>
    
    </div>

</body>
</html>