<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

<link href='http://fonts.googleapis.com/css?family=Ubuntu' rel='stylesheet' type='text/css'>

<title><?=$tpl->exception?></title>

<style type="text/css">

body {
	padding:0px;
	margin:0px;
	background-color:#ffffff;
	background-repeat: repeat-x;
	background-position: top;
}

#wrapper {
	position:absolute;
	top:50%;
	left:50%;
	width:500px;
	height:200px;
	margin-left:-250px;
	margin-top:-100px;

}

#head {
	width:482px;
	height:42px;
	background-color:#2D2D2D;

	color:#ffffff;
	font-family:Ubuntu;
	padding:22px 0px 0px 20px;
	font-size:15px;
	overflow:hidden;
	
	border-top-left-radius:3px;
	border-top-right-radius:3px;
}


#body {
	padding:20px;
	font-size:12px;
	text-align:center;
	
	background-color:#F1F1F1;
	border:1px solid #D2D2D2;

	border-top:0px;
	width:460px;

	border-bottom-left-radius:3px;
	border-bottom-right-radius:3px;
}

#logo {
	
	font-family:Ubuntu;
	text-decoration:none;
	font-size:50px;
	color:#ffffff;

	display:block;
	margin-top:-22px;
	margin-right:-1px;
	float:right;
	/*opacity:0.3;
	filter:alpha(opacity=30);*/
	overflow:hidden;
	
	height:52px;
	border-radius:3px;
	
	
	padding:6px 21px 5px 20px;
}

#logo:hover {
	background-color: #357AE8;
	background-image: -webkit-linear-gradient(top,#4d90fe,#357AE8);
	background-image: -moz-linear-gradient(top,#4d90fe,#357AE8);
	background-image: -ms-linear-gradient(top,#4d90fe,#357AE8);
	background-image: -o-linear-gradient(top,#4d90fe,#357AE8);
	background-image: linear-gradient(top,#4d90fe,#357AE8);
	border:1px solid #3079ED;
	color:#ffffff;
	padding:5px 20px 5px 20px;
}

#login_form table {
	text-align:right;
	width:280px;
	margin:0px auto;
}


#login_form table tr td:last-child {
	padding-left:0px;
}

#login_form input[type=text], #login_form input[type=password]
{
	width:200px;
	border:1px solid #464646;
	padding:2px;
	font-size:18px;
	font-family:Arial;
	color:#464646;
	background:none;
	border-radius:2px;
	margin-bottom:5px;
	background-color:#ffffff;
}

#login_form input[type=button], #login_form input[type=submit]
{
	color:#ffffff;
	padding:8px 15px 8px 15px;
	font-size:12px;
	cursor:pointer;
	
	background-color: #4D90FE;
	background-image: -webkit-linear-gradient(top,#4d90fe,#4787ed);
	background-image: -moz-linear-gradient(top,#4d90fe,#4787ed);
	background-image: -ms-linear-gradient(top,#4d90fe,#4787ed);
	background-image: -o-linear-gradient(top,#4d90fe,#4787ed);
	background-image: linear-gradient(top,#4d90fe,#4787ed);
	
	border:1px solid #3079ED;
	border-radius:2px;
}

#login_form input[type=button]:hover, #login_form input[type=submit]:hover
{
	background-color: #357AE8;
	background-image: -webkit-linear-gradient(top,#4d90fe,#357AE8);
	background-image: -moz-linear-gradient(top,#4d90fe,#357AE8);
	background-image: -ms-linear-gradient(top,#4d90fe,#357AE8);
	background-image: -o-linear-gradient(top,#4d90fe,#357AE8);
	background-image: linear-gradient(top,#4d90fe,#357AE8);
}

#login_form input[type=button]:active, #login_form input[type=submit]:active
{
	-moz-box-shadow: inset 0 1px 2px rgba(0,0,0,0.3);
	-ms-box-shadow: inset 0 1px 2px rgba(0,0,0,0.3);
	-o-box-shadow: inset 0 1px 2px rgba(0,0,0,0.3);
	-webkit-box-shadow: inset 0 1px 2px rgba(0,0,0,0.3);
	box-shadow: inset 0 1px 2px rgba(0,0,0,0.3);
}


</style>



</head>
<body>

<div id="wrapper">

    <div id="head">
    	<div id="logo">fermi</div>
		<?=I18n::_('login_box_head')?>
    </div>
    
    <div id="body">
    
     	<?=I18n::_($tpl->message)?>

		<?php
		
			if(Util::is_ie6())
			{
				echo I18n::_('browser_not_capable') ;
			}
			else
			{
				echo $tpl->form ;
			}

		?>
    </div>

</div>

</body>
</html>

