<?php

$extract = function($article_collection) use (&$extract) {
	
	echo '<ul class="">' ;
	
	foreach($article_collection as $article)
	{
		echo '<li id="a'.$article->getId().'">' ;
		
		echo '<a href="" id="article_'.$article->getId().'">'.$article->name.'</a>' ; 
		
		$children = $article->getChildren() ;
		
		if(count($children) != 0)
		{
			$extract($children) ;
		}
		
		echo '</li>' ;
	}
	
	
	
	echo '</ul>' ;
	
} ;

?>

<script type="text/javascript">

$(document).ready(function(){
 	var tree_transaction_log = {test: 'bla'} ;

	$('.structure_tree').jstree({
		core : { /* core options go here */ },
		
		
		plugins : [ "themes", "html_data", 'crrm', 'dnd', 'json_data', 'cookies'],
		
	});
	
	$('.structure_tree').bind('move_node.jstree', function(e, data) {
		
		var target = data.args[0]['cr'] ;
		var node_id = data.args[0]['o']['context']['id'].substring(8) ;
		
		if(typeof target != 'object')
		{	
			var target_id = 'NULL'
		}
		else
		{
			var target_id = target['context']['id'].substring(8) ;
		}
		
		tree_transaction_log[''+node_id+''] = target_id ;
		
		$('#structure_tree_save').removeAttr('disabled');
		
	}) ;
	
	var timer ;
	
	$('#structure_tree_save').click(function() {
		
		$('.save_loader').attr('src', '<?=$tpl->skin?>img/loader.gif') ;
		$('.save_loader').css({opacity:1}) ;
		
		$('#structure_tree_save').attr('disabled', 'disabled');
		
		clearTimeout(timer) ;
		
		timer = setTimeout(function() {
			
			$('.save_loader').attr('src', '<?=$tpl->skin?>img/checkmark.png') ;
			
			$('.save_loader').stop(true).delay(500).animate({opacity: 0}) ;
			
		}, 2000) ;
		
		
	}) ;
	
	/*$('#json').click(function() {
		
		console.log(JSON.stringify($('.structure_base_container').jstree('get_json'), {}, '	')) ;
		
	}) ;*/
	
}) ;

</script>

<div class="structure_wrapper">

<div class="structure_base_container">
	

<div class="structure_tree">
<?php

	$extract($tpl->root_articles) ;

?>
</div>

<div class="structure_actions">
	
	<img class="save_loader" src="<?=$tpl->skin?>img/loader.gif" alt="" />
	<button id="structure_tree_save" disabled="disabled"><?=I18n::_('save')?></button>
	
</div>

</div>

<div class="structure_content">
	<h1><?=I18n::_('Structure')?>: <?=Request::get('action')?></h1>
	
	
</div>


<br style="clear:both;" />
</div>