<?php

$extract = function($category, $indent) use (&$extract) {
		
	$children = $category->getChildren() ;
	$articles = $category->getArticles() ;
	
	echo '<div class="structure_category_container" style="margin-left:'.($indent).'px">
	<span class="structure_category_label">'.$category->name.'</span>' ;
	
	$indent = $indent + 20 ;
	
	foreach($children as $child)
	{
		
		$extract($child, $indent) ;
		
	}
	
	echo '<ul class="structure_category">' ;
	
	foreach($articles as $article)
	{
		echo '<li class="structure_article"><span class="structure_article_label">'.$article->name.'</span></li>' ;
	}

	echo '</ul></div>' ;
} ;

?>
<script type="text/javascript" src="<?=Registry::getModuleUri('articles')?>index.js"></script>

<div class="structure_base_container">
	


<?php

foreach($tpl->categories as $category)
{
	$extract($category, 0) ;
}
?>

<ul class="structure_base">
<?php

foreach($tpl->articles as $article)
{
	echo '<li class="structure_article"><span class="structure_article_label">'.$article->name.'</span></li>' ;
}


?>
</ul>

</div>