<?php

$extract = function($article_collection) use (&$extract) {
	
	echo '<ul class="">' ;
	
	foreach($article_collection as $article)
	{
		echo '<li>' ;
		
		echo '<a href="#">'.$article->name.'</a>' ; 
		
		$children = $article->getChildren() ;
		
		if(count($children) != 0)
		{
			$extract($children) ;
		}
		
		echo '</li>' ;
	}
	
	
	
	echo '</ul>' ;
	
} ;

?>
jQuery("some-selector-to-container-node-here")

    .jstree({

        core : { /* core options go here */ },

        plugins : [ "themes", "html_data", "some-other-plugin" ]

    });

<div class="structure_base_container">
	


<?php

	$extract($tpl->root_articles) ;



?>



</div>